### Site info:
title: Ha1oS3c
tagline: 华软网络安全小组s' Blog
email: sise_nsg@sina.cn
description: "HSTONS,华软网络安全小组" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "华软网络安全小组, HaloSec, Sise"
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://halosec.org" # the base hostname & protocol for your site
locale: en_US
permalink: /Categories/:categories/:year/:month/:day/:title.html
### Personal info and site tools info:
twitter_username: HaloSec
github_username:  HaloSec
disqus_shortname: Ha1oS3c
weibo_username: HaloSec
favicon:     "/images/favicon.ico"
aboutme: HSTONS,是由华软学子组成的网络安全兴趣小组,小组内有研究逆向破解,Web安全,硬件的等方向的成员。 # these are shown on aboutme-sidebar.
aboutme_photo: "/images/Ha1oS3c.jpg" #your photo.
google_analytics_key: UA-59291875-2 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Author: "Member"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      Postedwith: "and Posted"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: "关于我们"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Author: "成员"
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      Postedwith: "| 作者:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: redcarpet
highlighter: pygments
paginate: 5
excerpt_separator: <!-- more -->
